# top level stuff you probably don't need to touch
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://www.adeyemiolaoye.me/
baseurl: /
title: Adeyemi Olaoye | Software Engineer
author: Adeyemi Olaoye
description: Adeyemi Olaoye
avatar: profile.png
email: yemexx1@gmail.com
github: yemexx1 # username
twitter: yemexx1
linkedin: adeyemi-olaoye-36726749
stackoverflow: users/1215010/adeyemi   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
tagmanager_id: GTM-M2H47X


# needed for travis-ci build
exclude: [vendor]
